version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Client
          command: npm run heroku-postbuild
      - run:
          name: Start Server
          command: npm start
          background: true
      - run:
          name: Run Tests
          command: npm run cypress:test