version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.7.0-chrome84
        environment:
          ## this enables colors in the output
          TERM: xterm
      - image: circleci/postgres:12-alpine
        # auth:
        #   username: root
        #   password: $POSTGRES_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: clipcrab
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Client
          command: yarn build:ci
          env:
            CI: ""
      - run:
          name: Build Database
          command: ./node_modules/ts-node/dist/bin.js ./node_modules/typeorm/cli.js schema:sync
      - run:
          name: Start Server
          command: yarn start:test
          background: true
      - run:
          name: Run Cypress Tests
          command: yarn cypress:test
      - run:
          name: Run Mocha Tests
          command: yarn test