version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run heroku-postbuild
      - cypress/run:
          yarn: true
          start: npm start
          wait-on: 'http://localhost:3001'