version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Client
          command: npm run heroku-postbuild
          env:
            CI: ""
      - run:
          name: Start Server
          command: npm start
          background: true
      - run:
          name: Run Tests
          command: npm run cypress:test