version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/base:14.10.1
        environment:
          ## this enables colors in the output
          TERM: xterm
      - image: circleci/postgres:12-alpine
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: clipcrab
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Client
          command: yarn build:ci
          env:
            CI: ""
      - run:
          name: Build Database
          command: ./node_modules/ts-node/dist/bin.js ./node_modules/typeorm/cli.js migration:run
      - run:
          name: Start Server
          command: yarn start
          background: true
      - run:
          name: Run Tests
          command: yarn cypress:test